language: perl
sudo: false
perl:
- '5.8'
- '5.24'
env:
  global:
  - PERL_MM_USE_DEFAULT=1 TEST_AUTHOR=1
  - secure: VTNBgfisvVGIiVRCNp+jkoEGqrxnM90vOUW2bq9maxCbxmF47Y3mIHqzDTt/hK4z9REuTiElp6jlnlKuSvwrSndzPKWVAdXtrenUcKCrKCDRoNRvDoJ4EfLZ+5fPU3AhdNFeMfLNhj9oiIi7ysc3RWuP7TWIpyQYJccqwfcfTXYMR2GyAUvjAvMohtQGoFMgRwhZDNDIKJI+JVPg6efXwZZ1wu6p0ldqMvoEiJOhqwpKhmC9yEBqnR3EYR3ZLrOAm9qFuXnMjav9cPv1tUbNAvFofgzh1/Ik6uOx5JFw7ZV3FV7+2AN4QoUHijqb81Qfa+eYk6nfr2lrHYU2sLPUolN2AVbBW/wBKCdy9Rtevs1HrEOqW6g9ciChjr881k+n2c6zqpQBZgME0Q6nzsiC5kNsme9A0QEHyEl6yZCpcE+40RGIuNCYVD/qRnPytZjxxZm80TRvALjub2bb162DseEeh4fTrVksAAimRpI0w+xXDaEtP2mhoub7rNsjZTlJqYnDj+U8bwozccGcSUiezZypXO43/041Vl+AgI3r+OJvlzsn+q5E6gDBhM5f0mvM2jYMRXWvDLw4fhFHHXd79+rNWSq4jVb4pGmd+aZ8Q7lFCZYnrP2quLtOZYn38Jc+lSH8CXMtRTRdGqfIJ489QL431lVNzMzWZn1TduBvcmo=
  - secure: gwqi78iHGrho8IAX5qDz6tUQayeAm8wmahlKc9v8eoUSgFUfZg/GGdDqQ3s7OQc1QtfPG28hmDRt2ealyIsoZINaCV6XRunWQa/Qec8VV3giN8vKHJJRg0qCrJkxNO4LDphMzuiPFM3TqhK5zAfSUtryZuOTy1j5V8f18mpFN04SuCY0Ucgj257F/nJ4tcaQMSAhAvai5D0rLTsjMb0FHrp7JQdlVfEGUJfkclznniJ3BXsklU5m2a73WFyiDePkaXBZxhUAbnKf6bHkKkUJCqhaG50w8o7xfG27Yr3iDOzvnsO3kz3H+qS23FEH1scs+KHxwM//hvIK/i7mSz0TrBjIMSfPT9EESN6B4e2/WVz8msgRQHDE+JaN8UKplvTS47gTEAO7mgBNL5b0BBJQqqhaQS8/3zf0pq65IuGZcUdxlOsZAtfLMOZDXIs18aku748j25K2hKqJXGAWLMGKB8XkPYW+rhItbZ9eAWisRp4w/tYYLHh3lhSHVaa3oNsLAUDaQh8xhwU0OighxqN8PTRP588D4TJuVl6Ncn/PCWJNrQhQ5J2yj2TN0pYSw+sglrx5na5XNC6fyKCBOJaO8fHT8MMaPdXT6HIFEzG6K7JkMB0zdsDRbcwFxhx1bwdGa1NM9mvBEOvEqzFaP6FQVKMKiorTpxHyigDx28ZlFnc=
  - secure: SrkB6s4rhEUr5m/IakDW2aCLxDfTjVJJL2tmHOVTUzz/Xaz4tuXWERQ2Y4HanxH5iIJiNYVS5pgOFxSxWd61UshcAWEFQxknV7Cs3+HZDy5S6SM+Nw2Pqs/QkTzVGUWnmOW0V2Kz06K0GF0IRXgADKmihhu8ZINu+OTE9rVVkmXIcDLLNokpZU66eoLvOIjCnT1lrEEgSSz67/v8AY8ts3curYRc4hFO5k+uoBPIATIly6ugs65XXCBVAjTMwLusPZFeRt6QPYyZJ9Tjp4ZmMf/jDMJ03qCcdpdLMgtGYqpZ+ICCL5AkjToc8cCDHUC/KPBlYvnfK5PGg2jfg1ayAPOJ7PxHDRw25r3NJVZRyd9Gjs1sPy1nyRxcOk0k6qdbfpCfuSpx4yb/lS0gHl9FpmQu005hH2iOu96zFwSC8LQrOsyUxqZrggC5aqEWrgd8GWG7W/ZmIJeBNa6LDlgYgMiT+wawBJIMNZ+QY+XycEDvSodp4VxBKxxUcOdbWLTVxe1hMmoOMwHcnnWgAiC796/lNdG8VmIIwf7WPjk0qPrC8rD+EfbmDkDmlQuvLm3iKXrJhmAgG+INxTWDS4PNxeCvZnO9Jg4V+r/7KJARZb6/OiUFlmPlq5RzrBwUMJ+jpDiOAx70LSHlPQ23WohQFV7oCZUTZfTjQDLtKDT/FWU=
cache:
  directories:
  - perl_modules
before_install:
- git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
- source ~/travis-perl-helpers/init
- build-perl
- perl -V
- cpanm --notest local::lib
- eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
- build-dist
- cd $BUILD_DIR
script:
- make test
